# Generated by Django 2.0.7 on 2018-08-05 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('register_plate', models.CharField(max_length=50)),
                ('consumption', models.DecimalField(decimal_places=2, default=None, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('inappropriate', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=50)),
                ('departure', models.CharField(max_length=50)),
                ('available_seats', models.IntegerField()),
                ('status', models.CharField(choices=[('ONGOING', 'ongoing'), ('COMPLETED', 'completed')], max_length=10)),
                ('ride_ended', models.DateTimeField(default=None)),
                ('estimated_fuel_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('recurrent', models.CharField(choices=[('ONE_TIME', 'one_time'), ('DAILY', 'daily'), ('WEEKLY', 'weekly'), ('MONTHLY', 'MONTHLY')], default='ONE_TIME', max_length=1)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv1.Car')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(default=None, max_length=1000)),
                ('photo', models.CharField(default=None, max_length=50)),
                ('reported', models.IntegerField(default=0)),
                ('deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('driver_rating', models.DecimalField(decimal_places=2, default=None, max_digits=3)),
                ('driver_reviews', models.IntegerField(default=0)),
                ('passenger_rating', models.DecimalField(decimal_places=2, default=None, max_digits=3)),
                ('passenger_reviews', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_rides', to='apiv1.User'),
        ),
        migrations.AddField(
            model_name='ride',
            name='passengers',
            field=models.ManyToManyField(to='apiv1.User', verbose_name='passengers'),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='apiv1.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='apiv1.Ride'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='apiv1.User'),
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='apiv1.User'),
        ),
    ]
