from apiv1.views.root import *
from apiv1.views.user import *
from apiv1.views.profile import *
from apiv1.views.rides import *
from apiv1.views.passenger import *
from apiv1.views.car import *
from apiv1.views.request import *
from apiv1.views.user_rides_as_driver import *
from apiv1.views.user_rides_as_passenger import *
from apiv1.views.user_requests import *
from apiv1.views.end_ride import *
from apiv1.views.accept_request import *