# Generated by Django 2.0.7 on 2018-08-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0002_ride_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='total_seat_count',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='ride',
            name='available_seats',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='recurrent',
            field=models.CharField(choices=[('ONE_TIME', 'one_time'), ('DAILY', 'daily'), ('WEEKLY', 'weekly'), ('MONTHLY', 'monthly')], default='one_time', max_length=1),
        ),
    ]
