# Generated by Django 2.1 on 2018-08-23 13:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0003_auto_20180820_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(default='Volvo', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='consumption',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='register_plate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ride',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiv1.Car'),
        ),
    ]
