# Generated by Django 2.1 on 2018-08-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0003_auto_20180813_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privateprofile',
            name='token',
        ),
        migrations.AddField(
            model_name='privateprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='privateprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
