# Generated by Django 2.1 on 2018-08-28 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0004_auto_20180823_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='car',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='apiv1.Car'),
            preserve_default=False,
        ),
    ]
