# Generated by Django 2.1 on 2018-08-13 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apiv1', '0004_auto_20180813_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_count', models.PositiveIntegerField(default=0)),
                ('deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='privateprofile',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='privateprofile',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='privateprofile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='privateprofile',
            name='reported',
        ),
    ]
