# Generated by Django 2.1 on 2018-08-13 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0005_auto_20180813_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privateprofile',
            name='email',
        ),
    ]
