# Generated by Django 2.1 on 2018-08-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0006_auto_20180830_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('ONGOING', 'ongoing'), ('COMPLETED', 'completed')], default='ONGOING', editable=False, max_length=10),
        ),
    ]
