# Generated by Django 2.1 on 2018-08-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0007_auto_20180830_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='recurrent',
            field=models.CharField(choices=[('ONE_TIME', 'one_time'), ('DAILY', 'daily'), ('WEEKLY', 'weekly'), ('MONTHLY', 'monthly')], default='ONE_TIME', max_length=1),
        ),
    ]
