# Generated by Django 2.1 on 2018-09-16 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0008_auto_20180831_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
