# Generated by Django 2.1 on 2018-09-18 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0009_ride_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='time',
        ),
    ]
